name: cross_platform_video_thumbnails_example
description: Example app for the cross_platform_video_thumbnails package
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  cross_platform_video_thumbnails:
    path: ../
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
